spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  mvc:
    static-path-pattern: /static/**

server:
  port: 8080

tbp:
  store-dir: C:\Users\SayYi\Desktop\temp\tbpStore
  snap-dir: C:\Users\SayYi\Desktop\temp\tbpSnap