spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  mvc:
    static-path-pattern: /static/**

server:
  port: 8080

logging:
  level:
    root: info

tbp:
  nio:
    enable: false
    port: 9000
  snap-dir: D:\\pkm\\snap
  store-dir: D:\\pkm\\store
  tree-retain-num: 10