spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  mvc:
    static-path-pattern: /static/**

# web监听端口
server:
  port: 8080

# 日志等级
logging:
  level:
    root: info

tbp:
  # nio配置。如果启用nio，需要先启动tbpServer.cmd
  nio:
    enable: false
    # tcp server 监听端口，需要和tbp.cfg中配置的端口相同
    port: 9000
  # 元数据存储目录
  snap-dir: D:\\pkm\\snap
  # 文件存储目录
  store-dir: D:\\pkm\\store
  # 目录树保留的历史版本数量
  tree-retain-num: 10