server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  mvc:
    static-path-pattern: /static/**

tbp:
  store-dir: D:\pkm\store
  snap-dir: D:\pkm\snap