spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  mvc:
    static-path-pattern: /static/**

server:
  port: 9000

logging:
  level:
    root: info
    com:
      sayyi:
        software:
          tbp: debug

tbp:
  nio:
    enable: false
    port: 9000
  snap-dir: C:\\Users\\SayYi\\Desktop\\temp\\tbpSnap
  store-dir: C:\\Users\\SayYi\\Desktop\\temp\\tbpStore
  tree-retain-num: 10